version = 0.1
[default.deploy.parameters]
stack_name = "ssosync"
resolve_s3 = true
s3_prefix = "ssosync"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ScheduleExpression=\"rate(15 minutes)\" LogLevel=\"warn\" LogFormat=\"json\" GoogleUserMatch=\"\" GoogleGroupMatch=\"\" IgnoreGroups=\"\" IgnoreUsers=\"\" IncludeGroups=\"aws\" SyncMethod=\"users_groups\""
image_repositories = []
